default: &default
  adapter: postgresql
  username:
  password:
  host: localhost

development:
  <<: *default
  database: qanda_development

test:
  <<: *default
  database: qanda_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 25 %>
