default: &default
  adapter: postgresql
  username: test
  password: 1234test
  host: localhost

development:
  <<: *default
  database: qanda_development

test:
  <<: *default
  database: qanda_test

production:
  <<: *default
  database: qanda_production
